apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-restapi-database-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-restapi-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-restapi
    ports:
    - protocol: TCP
      port: 5432
