apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-restapi-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - name: resapi
      protocol: TCP
      port: {{ .Values.restapiContainerPort }}
      targetPort: {{ .Values.restapiContainerPort }}
      nodePort: {{ .Values.restapiExposedPort }}