apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-restapi
spec:
  replicas: {{ .Values.restapireplicaCount }}
  template:
    metadata:
      name: python-app
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: madadian/restapi
        workingDir: /usr/src/app
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-restapi-database-con
          - secretRef:
              name: {{ .Release.Name }}-restapi-database-pass
        ports:
          - containerPort: {{ .Values.restapiContainerPort }}
  selector:
    matchLabels:
      app: python-app
